spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 5566
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8082

account:
  confirm:
    base-url: "localhost"
